### ISSUE TITLE
[META] Manim Slides v5 and call for contributors

### ISSUE THREAD

**Issue by jeertmans** [jeertmans/manim-slides#208]
Hello everyone,

After more than one year of existence, Manim Slides has gained many cool features, and is a tool I hope many find useful for presenting maths related content.

Even though the current set of features is, in my opinion, quite complete, I would love to see Manim Slides be improved on multiple aspects. As I am quite busy with my daytime work, **I am calling for contributors**, in the hope to accelerate Manim Slides' development.

I have organised this *META* issue in three parts: **who** I think could help me, **what** kind of help I am looking for, and **how** you can actually help me improve this project.

# Who

Actually, anyone that is willing to help me, and knows a bit of Python, is welcome!

Knowledge about Manim or Manim Slides is not that important, since Manim Slides imports only few things from Manim, and most of the logic is based on converting and presenting slides.

# What

Here are a few things[^1] I had in mind:

[^1]: :green_heart: for *easy*, :blue_heart: for *medium*, and :heart: for *hard*. 

- [x] :green_heart: Support TOML configuration files (using `rtoml` most probably), because JSON is hard to edit or read by a human;
- [x] :heart: Fix ordering issue when multiple scenes are played (see #205). This might need rewriting the video-player (see below);
- [x] :blue_heart: Improving the current test coverage by writing new tests in the `tests/` folder. Tests are important because they can help find bugs, and could help prevent issues like #205.

Features that are most probably breaking changes:

- [x] Rewriting the player to optionally support audio (thanks to PySide6's [`QMediaPlayer`](https://doc.qt.io/qtforpython-6/PySide6/QtMultimedia/QMediaPlayer.html)) (see #243).
- [x] :green_heart: Change the current user config file so that it will be able to support more things in the future. This can probably be done by moving the keys definitions inside some `[keys]` section;

The latter features are the reason why I mention a `v5` for Manim Slides.

# How

If you are already familiar with the usual contributing process on GitHub, then please feel free to create an issue or a pull request!

Otherwise, I wrote a [short contributing guide](https://eertmans.be/manim-slides/contributing/index.html) to help you. If you feel like something is missing in this guide, please reach out to me!

If you have any question or suggestion, please feel free to use the comments section :-)

Thanks!
