### ISSUE TITLE
[FEATURE] Automatically skip some slide

### ISSUE THREAD

**Issue by jeertmans** [jeertmans/manim-slides#302]
### Discussed in https://github.com/jeertmans/manim-slides/discussions/301

The suggestion is to add some parameter, e.g., `auto_skip=True`, to `Slide.next_slide` to that some slide may be skipped automatically.

# TODOs

- [ ] Check compatibility with `loop=True`, and maybe prevent that both are equal to `True`
- [ ] Add a new option to the `SlideConfig` and document it
- [ ] Watch for `EndOfMedia` with `present` and skip if needed
- [ ] Check if this can be supported by RevealJS and/or PowerPoint?

<div type='discussions-op-text'>

<sup>Originally posted by **Adcombrink** October 25, 2023</sup>
Loving manim-slides so far, great work. However, I've been trying to do something and am starting to think it's not possible, maybe a new feature. I want to click to the next slide, have an animation play, and then loop another animation, all with only clicking the first time. Right now, if i write 

```python
self.next_slide()

self.play(... initial animations ...)
self.start_loop()
self.play(... looping animations ...)
self.end_loop()
``` 
then it instantly jumps to the looping part, as if the initial animations have already run. </div>

**Comment by Adcombrink** [comment]
Nice! Thanks for the good work!
