### ISSUE TITLE
META: add missing type hints

### ISSUE THREAD

**Issue by jeertmans** [jeertmans/manim-slides#34]
# What

Some files have functions with missing type hints in their signature.

Here is an up-to-date list of files to complete:

- [ ] [manim_slides/commons.py](https://github.com/jeertmans/manim-slides/blob/main/manim_slides/commons.py)
- [ ] [manim_slides/config.py](https://github.com/jeertmans/manim-slides/blob/main/manim_slides/config.py)
- [ ] [manim_slides/defaults.py](https://github.com/jeertmans/manim-slides/blob/main/manim_slides/defaults.py)
- [ ] [manim_slides/manim.py](https://github.com/jeertmans/manim-slides/blob/main/manim_slides/manim.py)
- [ ] [manim_slides/present.py](https://github.com/jeertmans/manim-slides/blob/main/manim_slides/present.py)
- [ ] [manim_slides/slide.py](https://github.com/jeertmans/manim-slides/blob/main/manim_slides/slide.py)
- [ ] [manim_slides/wizard.py](https://github.com/jeertmans/manim-slides/blob/main/manim_slides/wizard.py)

# How to contribute

Please modify file(s) such that:

* every function should have a type hint for each parameter, and for return parameter (except if `None`),
* type hints should be compatible with Python 3.7 (so things like `x: str | None` are not accepted, instead use `x: Optional[str]`),
* `self` in methods should not take any type hint,
* constant declaration should have type hint (e.g., `MANIM_AVAILABLE: bool = ...`),
* and use types from `Typing` module only when necessary (so prefer `list` over `typing.List` if the list elements type is `Any`).

# Multiple PRs

Since the number of files to be changed is large, feel free to only modify one file or so per PR.

**Comment by elliotwutingfeng** [comment]
I'm interested in working on this!
